# Generated by Django 3.2.5 on 2022-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('people', models.IntegerField(blank=True, null=True)),
                ('child_in_group', models.BooleanField(blank=True, null=True)),
                ('elder_in_group', models.BooleanField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('current_city', models.CharField(blank=True, max_length=150, null=True)),
                ('days', models.IntegerField(blank=True, null=True)),
                ('radius', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searchs',
            },
        ),
    ]
