# Generated by Django 3.2.5 on 2022-04-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='username',
            field=models.CharField(default='anonymous', max_length=50),
        ),
    ]
