# Generated by Django 3.2.5 on 2022-04-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_search_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='search',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
