# Generated by Django 3.2.5 on 2022-04-22 18:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_auto_20220423_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='time_stamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
